heat_template_version: 2014-10-16

# NOTE: You don't need to pass the parameter explicitly from the
# parent template, it can be specified via the parameter_defaults
# in the resource_registry instead, if you want to override the default
# and/or share values with other templates in the tree.
parameters:
  ContrailRepo:
    type: string
    default: http://192.0.2.1/contrail
  VrouterPhysicalInterface:
    default: 'eth0'
    description: vRouter physical interface
    type: string
  VlanParentInterface:
    default: ''
    description: Parent interface of vlan interface
    type: string
  BondInterface:
    default: ''
    description: Bond interface name
    type: string
  BondInterfaceMembers:
    default: ''
    description: Bond interface members
    type: string


description: >
  This is an example showing how you can do firstboot configuration
  of the nodes via cloud-init.  To enable this, replace the default
  mapping of OS::TripleO::NodeUserData in ../overcloud_resource_registry*

resources:
  userdata:
    type: OS::Heat::MultipartMime
    properties:
      parts:
      - config: {get_resource: vrouter_module_config}

  vrouter_module_config:
    type: OS::Heat::SoftwareConfig
    properties:
      config:
        str_replace:
          template: |
            #!/bin/bash
            #sed -i '/\[main\]/a \ \ \ \ \parser = future' /etc/puppet/puppet.conf
            cat <<EOF > /etc/yum.repos.d/contrail.repo
            [Contrail]
            name=Contrail Repo
            baseurl=$contrail_repo
            enabled=1
            gpgcheck=0
            protect=1
            EOF
            if [[ `hostname |awk -F"-" '{print $2}'` == "contrailcontroller" || `hostname |awk -F"-" '{print $2}'` == "contrailanalytics" || `hostname |awk -F"-" '{print $2}'` == "contrailanalyticsdatabase" ]]; then
              sed -i '/\[main\]/a \ \ \ \ \parser = future' /etc/puppet/puppet.conf
              yum install -y contrail-tripleo-puppet puppet-contrail
              rsync -a /usr/share/contrail-tripleo-puppet/ /usr/share/openstack-puppet/modules/tripleo/
            fi
            if [[ `hostname |awk -F"-" '{print $2}'` == "contrailanalytics" ]]; then
              yum remove -y python-redis
            fi
            if [[ `hostname |awk -F"-" '{print $2}'` == "controller" ]]; then
              yum install -y contrail-tripleo-puppet puppet-contrail
              rsync -a /usr/share/contrail-tripleo-puppet/ /usr/share/openstack-puppet/modules/tripleo/
            fi
            if [[ `hostname |awk -F"-" '{print $2}'` == "novacompute" || `hostname |awk -F"-" '{print $2}'` == "contrailtsn" ]]; then 
              yum install -y contrail-tripleo-puppet puppet-contrail
              rsync -a /usr/share/contrail-tripleo-puppet/ /usr/share/openstack-puppet/modules/tripleo/
              yum install -y contrail-vrouter-utils
              function pkt_setup () {
                  for f in /sys/class/net/$1/queues/rx-*
                  do
                      q="$(echo $f | cut -d '-' -f2)"
                      r=$(($q%32))
                      s=$(($q/32))
                      ((mask=1<<$r))
                      str=(`printf "%x" $mask`)
                      if [ $s -gt 0 ]; then
                          for ((i=0; i < $s; i++))
                          do
                              str+=,00000000
                          done
                      fi
                      echo $str > $f/rps_cpus
                  done
                  ifconfig $1 up
              }
              function insert_vrouter() {
                  insmod /tmp/vrouter.ko
                  if [ -f /sys/class/net/pkt1/queues/rx-0/rps_cpus ]; then
                      pkt_setup pkt1
                  fi
                  if [ -f /sys/class/net/pkt2/queues/rx-0/rps_cpus ]; then
                      pkt_setup pkt2
                  fi
                  if [ -f /sys/class/net/pkt3/queues/rx-0/rps_cpus ]; then
                      pkt_setup pkt3
                  fi
                  DEV_MAC=$(cat /sys/class/net/$phy_int/address)
                  vif --create vhost0 --mac $DEV_MAC
                  vif --add $phy_int --mac $DEV_MAC --vrf 0 --vhost-phys --type physical
                  vif --add vhost0 --mac $DEV_MAC --vrf 0 --type vhost --xconnect $phy_int
                  ip link set vhost0 up
                  return 0
              }
              yumdownloader contrail-vrouter --destdir /tmp
              cd /tmp
              rpm2cpio /tmp/contrail-vrouter*.rpm | cpio -idmv
              cp `find /tmp/lib/modules -name vrouter.ko |tail -1` /tmp
              if [ $bond_int ]; then
                 bond_int_member_list=$(echo $bond_int_members | tr "," "\n")
                 ip link add name $bond_int type bond
                 for member in $bond_int_member_list; do
                     ip link set dev $member master $bond_int
                 done
              fi 
              if [ $vlan_parent ]; then
                  vlanId=`echo $phy_int | awk -F"vlan" '{print $2}'`
                  ip link add name $phy_int link $vlan_parent type vlan id $vlanId
              fi
              insert_vrouter
              if [[ `ifconfig $phy_int |grep "inet "` ]]; then
                def_gw=''
                if [[ `ip route show |grep default|grep $phy_int` ]]; then
                  def_gw=`ip route show |grep default|grep $phy_int|awk '{print $3}'`
                fi
                ip=`ifconfig $phy_int |grep "inet "|awk '{print $2}'`
                mask=`ifconfig $phy_int |grep "inet "|awk '{print $4}'`
                ip address delete $ip/$mask dev $phy_int
                ip address add $ip/$mask dev vhost0
                if [[ $def_gw ]]; then
                  ip route add default via $def_gw
                fi
              fi
            fi
          params:
            $phy_int: {get_param: VrouterPhysicalInterface}
            $bond_int: {get_param: BondInterface}
            $bond_int_members: {get_param: BondInterfaceMembers}
            $vlan_parent: {get_param: VlanParentInterface}
            $contrail_repo: {get_param: ContrailRepo}

outputs:
  # This means get_resource from the parent template will get the userdata, see:
  # http://docs.openstack.org/developer/heat/template_guide/composition.html#making-your-template-resource-more-transparent
  # Note this is new-for-kilo, an alternative is returning a value then using
  # get_attr in the parent template instead.
  OS::stack_id:
    value: {get_resource: userdata}
