heat_template_version: queens

# NOTE: You don't need to pass the parameter explicitly from the
# parent template, it can be specified via the parameter_defaults
# in the resource_registry instead, if you want to override the default
# and/or share values with other templates in the tree.
parameters:
  RoleParameters:
    type: json
    description: Role Specific parameters
    default: {}
  ServiceNames:
    type: comma_delimited_list
    default: []
  deployment_actions:
    default: ['CREATE']
    type: comma_delimited_list
    description: >
      List of stack actions that will trigger any deployments in this
      templates. The actions will be an empty list of the server is in the
      toplevel DeploymentServerBlacklist parameter's value.
  server:
    type: string
  KernelArgs:
    default: ""
    type: string
    description: Kernel Args to apply to the host
    tags:
      - role_specific
  TunedProfileName:
    default: ""
    type: string
    description: Tuned Profile to apply to the host
    tags:
      - role_specific
  IsolCpusList:
    default: ""
    type: string
    description: >
      List of logical CPU ids whic need to be isolated from the host processes.
      This input is provided to the tuned profile cpu-partitioning to configure
      systemd and repin interrupts (IRQ repinning).
    tags:
      - role_specific
  ContrailSriovHugepages2MB:
    default: '2048'
    description: Number of 2MB hugepages
    type: string
  ContrailSriovHugepages1GB:
    default: ''
    description: Number of 1GB hugepages
    type: string
  ContrailVrouterModuleOptions:
    default: ''
    description: >
      Vrouter kernel module options.
      This string is passed to agent container as env variable VROUTER_MODULE_OPTIONS
      (by a chance if vrouter module is loaded by container) and
      it is saved as options in /etc/modprobe.d/vrouter.conf for a case
      when vrouter is loaded by ifup scripts called by os-collect-config from host.
      E.g. vr_mpls_labels=196000 vr_nexthops=521000 vr_vrfs=65536 vr_bridge_entries=1000000
    type: string
  ContrailSriovNumVFs:
    description: >
      Provide the list of VFs to be reserved for each SR-IOV interface.
      Format "<interface_name1>:<numvfs1>,<interface_name2>:<numvfs2>"
      Example "eth1:4096,eth2:128"
    type: comma_delimited_list
    default: ""
  ContrailDpdkDriver:
    default: 'uio_pci_generic'
    description: DPDK Nic Driver
    type: string
  ContrailDpdkOptions:
    default: ''
    description: >
      Vrouter dpdk advanced options.
      This string is passed to dpdk container as env variable DPDK_COMMAND_ADDITIONAL_ARGS,
      so dpdk command line is populated with arguments from this string.
      E.g. --vr_mempool_sz --dpdk_txd_sz --dpdk_rxd_sz
    type: string
  ContrailSriovMode:
    default: 'kernel'
    type: string
  ContrailRegistry:
    default: 'opencontrailnightly'
    description: Contrail Registry
    type: string
  ContrailImageTag:
    default: 'latest'
    description: Contrail container image tag
    type: string
  DockerContrailVrouterKernelInitImageName:
    description: image
    type: string
    default: "contrail-vrouter-kernel-init"
  DockerContrailVrouterKernelInitDpdkImageName:
    description: image
    type: string
    default: "contrail-vrouter-kernel-init-dpdk"
  DockerContrailVrouterAgentDpdkContainerName:
    description: image
    type: string
    default: "contrail-vrouter-agent-dpdk"
  DockerContrailVrouterAgentContainerName:
    description: image
    type: string
    default: "contrail-vrouter-agent"
  DockerContrailVrouterPluginInitImageName:
    description: >
      Vrouter plugin init container image name.
      It is a name of the vrouter plugin init image. It is
      for cases when third-party HW requires specific drivers to be installed.
      E.g. Mellanox requries some drivers on host to be installed.
      For Mellanox the image name is contrail-vrouter-plugin-mellanox-init-redhat
    type: string
    default: ''
  NodeDataLookup:
    type: json
    default: {}
    description: json string containing per-node configuration map
  ContrailSettings:
    default: {}
    description: Contrail Service settings
    type: json

description: >
  This template installs the Contrail dpdk packages in order
  to bring vhost0 interface up. Vhost0 interface must be up before
  os-net-config takes over.

conditions:
  deployment_actions_empty:
    equals:
      - {get_param: deployment_actions}
      - []
  is_dpdk:
    or:
      - {equals: [{get_param: ContrailSriovMode}, 'dpdk']}
      - {equals: [{get_param: [RoleParameters, ContrailSriovMode]}, 'dpdk']}

resources:
  DockerContrailVrouterKernelImageNormalize:
    type: ../../../tools/contrail/contrail-image-normalize.yaml
    properties:
      GenericImageName: {get_param: DockerContrailVrouterKernelInitImageName}

  DockerContrailVrouterKernelInitDpdkImageNormalize:
    type: ../../../tools/contrail/contrail-image-normalize.yaml
    properties:
      GenericImageName: {get_param: DockerContrailVrouterKernelInitDpdkImageName}

  DockerContrailVrouterAgentDpdkImageNormalize:
    type: ../../../tools/contrail/contrail-image-normalize.yaml
    properties:
      GenericImageName: {get_param: DockerContrailVrouterAgentDpdkContainerName}

  DockerContrailVrouterAgentImageNormalize:
    type: ../../../tools/contrail/contrail-image-normalize.yaml
    properties:
      GenericImageName: {get_param: DockerContrailVrouterAgentContainerName}

  DockerContrailVrouterPluginInitImageNormalize:
    type: ../../../tools/contrail/contrail-image-normalize.yaml
    properties:
      GenericImageName: {get_param: DockerContrailVrouterPluginInitImageName}

  ContrailSettingsRoleParametersValue:
    type: OS::Heat::Value
    properties:
      type: json
      value:
        map_replace:
          - map_replace:
            - contrail_settings: ContrailSettings
              sriov_num: ContrailSriovNumVFs
              hugepages_2mb: ContrailSriovHugepages2MB
              hugepages_1gb: ContrailSriovHugepages1GB
              vrouter_module_opts: ContrailVrouterModuleOptions
              dpdk_driver: ContrailDpdkDriver
              dpdk_options: ContrailDpdkOptions
            - values: {get_param: [RoleParameters]}
          - values:
              ContrailSettings: {get_param: ContrailSettings}
              ContrailSriovNumVFs: {get_param: ContrailSriovNumVFs}
              ContrailSriovHugepages2MB: {get_param: ContrailSriovHugepages2MB}
              ContrailSriovHugepages1GB: {get_param: ContrailSriovHugepages1GB}
              ContrailVrouterModuleOptions: {get_param: ContrailVrouterModuleOptions}
              ContrailDpdkDriver: {get_param: ContrailDpdkDriver}
              ContrailDpdkOptions: {get_param: ContrailDpdkOptions}

  SriovHostParametersConfig:
    type: OS::Heat::SoftwareConfig
    properties:
      group: ansible
      inputs:
        - name: _CONTRAIL_HUGEPAGES_1GB_
        - name: _CONTRAIL_HUGEPAGES_2MB_
        - name: _CONTRAIL_SRIOV_NUM_VFS_
        - name: _IS_DPDK_
      outputs:
        - name: result
      config:
        get_file: contrail_ansible_host_config.yaml

  SriovHostParametersDeployment:
    type: OS::Heat::SoftwareDeployment
    properties:
      name: SriovHostParametersDeployment
      server:  {get_param: server}
      config: {get_resource: SriovHostParametersConfig}
      actions:
        if:
          - deployment_actions_empty
          - []
          - ['CREATE'] # Only do this on CREATE
      input_values:
        _CONTRAIL_HUGEPAGES_1GB_: {get_attr: [ContrailSettingsRoleParametersValue, value, hugepages_1gb]}
        _CONTRAIL_HUGEPAGES_2MB_: {get_attr: [ContrailSettingsRoleParametersValue, value, hugepages_2mb]}
        _CONTRAIL_SRIOV_NUM_VFS_: {get_attr: [ContrailSettingsRoleParametersValue, value, sriov_num]}
        _IS_DPDK_: {if: [is_dpdk, 'True', '']}

  SriovContainerParametersConfig:
    type: OS::Heat::SoftwareConfig
    properties:
      group: ansible
      inputs:
        - name: _NODEDATA_
          type: Json
        - name: _CONTRAIL_SETTINGS_
          type: Json
        - name: _CONTRAIL_VROUTER_INIT_IMAGE_
        - name: _CONTRAIL_VROUTER_INIT_IMAGE_NAME_
        - name: _CONTRAIL_VROUTER_AGENT_DPDK_IMAGE_
        - name: _CONTRAIL_VROUTER_AGENT_DPDK_CONTAINER_NAME_
        - name: _CONTRAIL_VROUTER_MODULE_OPTS_
        - name: _CONTRAIL_VROUTER_PLUGIN_INIT_IMAGE_
        - name: _CONTRAIL_VROUTER_PLUGIN_INIT_IMAGE_NAME_
        - name: _CONTRAIL_DPDK_COMMAND_ADDITIONAL_ARGS_
        - name: _IS_DPDK_
      outputs:
        - name: result
      config:
        get_file: contrail_ansible_container_config.yaml

  SriovContainerParametersDeployment:
    type: OS::Heat::SoftwareDeployment
    properties:
      name: SriovContainerParametersDeployment
      server:  {get_param: server}
      config: {get_resource: SriovContainerParametersConfig}
      actions:
        if:
          - deployment_actions_empty
          - []
          - ['CREATE', 'UPDATE']
      input_values:
        _NODEDATA_: {get_param: NodeDataLookup}
        _CONTRAIL_SETTINGS_: {get_attr: [ContrailSettingsRoleParametersValue, value, contrail_settings]}
        _CONTRAIL_VROUTER_INIT_IMAGE_: {if: [is_dpdk, {get_attr: [DockerContrailVrouterKernelInitDpdkImageNormalize, contrail_image]}, {get_attr: [DockerContrailVrouterKernelImageNormalize, contrail_image]}]}
        _CONTRAIL_VROUTER_INIT_IMAGE_NAME_: {if: [is_dpdk, {get_attr: [DockerContrailVrouterKernelInitDpdkImageNormalize, contrail_image_only]}, {get_attr: [DockerContrailVrouterKernelImageNormalize, contrail_image_only]}]}
        _CONTRAIL_VROUTER_AGENT_DPDK_IMAGE_: {get_attr: [DockerContrailVrouterAgentDpdkImageNormalize, contrail_image]}
        _CONTRAIL_VROUTER_AGENT_DPDK_CONTAINER_NAME_: {get_attr: [DockerContrailVrouterAgentDpdkImageNormalize, contrail_image_only]}
        _CONTRAIL_VROUTER_MODULE_OPTS_: {get_attr: [ContrailSettingsRoleParametersValue, value, vrouter_module_opts]}
        _CONTRAIL_VROUTER_PLUGIN_INIT_IMAGE_: {get_attr: [DockerContrailVrouterPluginInitImageNormalize, contrail_image]}
        _CONTRAIL_VROUTER_PLUGIN_INIT_IMAGE_NAME_: {get_attr: [DockerContrailVrouterPluginInitImageNormalize, contrail_image_only]}
        _CONTRAIL_DPDK_COMMAND_ADDITIONAL_ARGS_: {get_attr: [ContrailSettingsRoleParametersValue, value, dpdk_options]}
        _IS_DPDK_: {if: [is_dpdk, 'True', '']}
    depends_on:
      - SriovHostParametersDeployment
      - DockerContrailVrouterPluginInitImageNormalize
      - DockerContrailVrouterKernelImageNormalize
      - DockerContrailVrouterAgentImageNormalize
      - DockerContrailVrouterAgentDpdkImageNormalize
      - DockerContrailVrouterKernelInitDpdkImageNormalize

  SriovKernelParametersConfig:
    type: OS::Heat::SoftwareConfig
    properties:
      group: ansible
      inputs:
        - name: _CONTRAIL_DPDK_DRIVER_
        - name: _CONTRAIL_SRIOV_NUM_VFS_
        - name: _CONTRAIL_HUGEPAGES_2MB_
        - name: _CONTRAIL_HUGEPAGES_1GB_
        - name: _TUNED_PROFILE_NAME_
        - name: _TUNED_CORES_
      outputs:
        - name: result
      config:
        get_file: contrail_ansible_kernel_config.yaml

  SriovKernelParametersDeployment:
    type: OS::Heat::SoftwareDeployment
    depends_on: [SriovContainerParametersDeployment]
    properties:
      name: SriovKernelParametersDeployment
      server:  {get_param: server}
      config: {get_resource: SriovKernelParametersConfig}
      actions:
        if:
          - deployment_actions_empty
          - []
          - ['CREATE'] # Only do this on CREATE
      input_values:
        _CONTRAIL_DPDK_DRIVER_: {get_attr: [ContrailSettingsRoleParametersValue, value, dpdk_driver]}
        _CONTRAIL_HUGEPAGES_1GB_: {get_attr: [ContrailSettingsRoleParametersValue, value, hugepages_1gb]}
        _CONTRAIL_HUGEPAGES_2MB_: {get_attr: [ContrailSettingsRoleParametersValue, value, hugepages_2mb]}
        _CONTRAIL_SRIOV_NUM_VFS_: {get_attr: [ContrailSettingsRoleParametersValue, value, sriov_num]}
        _KERNEL_ARGS_: {get_param: [RoleParameters, KernelArgs]}
        _TUNED_PROFILE_NAME_: {get_param: [RoleParameters, TunedProfileName]}
        _TUNED_CORES_: {get_param: [RoleParameters, IsolCpusList]}

  RebootConfig:
    type: OS::Heat::SoftwareConfig
    properties:
      group: script
      config: |
        #!/bin/bash
        # Stop os-collect-config to avoid any race collecting another
        # deployment before reboot happens
        # Do reboot only if it is really required.
        if [ -f /tmp/kernel_args_reboot_required.ansible ]; then
          rm -f /tmp/kernel_args_reboot_required.ansible
          systemctl stop os-collect-config.service
          /sbin/reboot
        fi

  RebootDeployment:
    type: OS::Heat::SoftwareDeployment
    depends_on: [SriovKernelParametersDeployment]
    properties:
      name: RebootDeployment
      server:  {get_param: server}
      config: {get_resource: RebootConfig}
      actions:
        if:
          - deployment_actions_empty
          - []
          - ['CREATE'] # Only do this on CREATE
      signal_transport: NO_SIGNAL

  RebootEnsureConfig:
    type: OS::Heat::SoftwareConfig
    properties:
      group: script
      config: |
        #!/bin/bash
        echo "Reboot completed"

  RebootEnsureDeployment:
    type: OS::Heat::SoftwareDeployment
    depends_on: RebootDeployment
    properties:
      name: RebootEnsureDeployment
      server:  {get_param: server}
      config: {get_resource: RebootEnsureConfig}
      actions:
        if:
          - deployment_actions_empty
          - []
          - ['CREATE'] # Only do this on CREATE

outputs:
  result:
    value:
      get_attr: [SriovKernelParametersDeployment, result]
  stdout:
    value:
      get_attr: [SriovKernelParametersDeployment, deploy_stdout]
  stderr:
    value:
      get_attr: [SriovKernelParametersDeployment, deploy_stderr]
  status_code:
    value:
      get_attr: [SriovKernelParametersDeployment, deploy_status_code]
