---
- name: Undercloud hosts
  hosts: localhost
  connection: local
  gather_facts: yes
  roles:
    - undercloud_hosts_group
  vars_files:
    - "{{ config_file }}"

- name: Configure undercloud
  hosts: undercloud_hosts
  gather_facts: no
  roles:
    - undercloud
  vars_files:
    - "{{ hostvars['localhost'].config_file }}"
