---
- name: undercloud nodes
  debug:
    msg: "{{ undercloud.nodes }}"

- name: kvm undercloud hosts (ssh username and pasword)
  add_host:
    hostname: "{{ item.value.ip }}"
    groupname: undercloud_hosts
    ansible_user: "{{ item.value.ssh_user | default(provider_config.kvm.ssh_user) }}"
    ansible_ssh_pass: "{{ item.value.ssh_pwd |default(provider_config.kvm.ssh_pwd) }}"
    ansible_become: true
    instance_name: "{{ item.key }}"
    private_ip: "{{ item.value.ip }}"
  when:
    - item.value.provider == 'kvm'
    - (item.value.ssh_pwd is defined or provider_config.kvm.ssh_pwd is defined)
  with_dict: "{{ undercloud.nodes }}"

- name: kvm undercloud hosts
  add_host:
    hostname: "{{ item.value.ip }}"
    groupname: undercloud_hosts
    ansible_become: true
    instance_name: "{{ item.key }}"
    private_ip: "{{ item.value.ip }}"
  when:
    - item.value.provider == 'kvm'
    - item.value.ssh_pwd is not defined
    - provider_config.kvm.ssh_pwd is not defined
  with_dict: "{{ undercloud.nodes }}"
