heat_template_version: queens

description:  Contrail Node init

parameters:
  server:
    type: string

resources:
  ContrailTlsInit:
    type: ./contrail-tls-inject.yaml
    properties:
      server: {get_param: server}

  ContrailNodeInit:
    type: ./contrail-node-init.yaml
    depends_on: [ContrailTlsInit]
    properties:
      server: {get_param: server}
      install_contrail_puppet: true

  ContrailIssuInit:
    type: OS::TripleO::ContrailIssuInit
    properties:
      server: {get_param: server}

outputs:
  contrail_tls_init:
    value: {get_resource: ContrailTlsInit}
  contrail_node_init:
    value: {get_resource: ContrailNodeInit}
  contrail_issu_init:
    value: {get_resource: ContrailIssuInit}
