heat_template_version: queens

description: >
  Contrail logrotate configuration
parameters:
  DockerCrondImage:
    description: image
    type: string
  DockerCrondConfigImage:
    description: The container image to use for the crond config_volume
    type: string
  EndpointMap:
    default: {}
    description: Mapping of service endpoint -> protocol. Typically set
                 via parameter_defaults in the resource registry.
    type: json
  ServiceData:
    default: {}
    description: Dictionary packing service data
    type: json
  ServiceNetMap:
    default: {}
    description: Mapping of service_name -> network name. Typically set
                 via parameter_defaults in the resource registry.  This
                 mapping overrides those in ServiceNetMapDefaults.
    type: json
  DefaultPasswords:
    default: {}
    type: json
  RoleName:
    default: ''
    description: Role name on which the service is applied
    type: string
  RoleParameters:
    default: {}
    description: Parameters specific to the role
    type: json
  LogrotateMaxsize:
    description: Configures the maxsize param for containerized logrotate.
    type: string
    default: '10M'
  LogrotateRotationInterval:
    description: Configures rotation interval for containerized logrotate.
    type: string
    default: 'daily'
    constraints:
      - allowed_values: [ 'daily', 'weekly', 'monthly' ]
  LogrotateRotate:
    description: Configures the rotate param for containerized logrotate.
    type: string
    default: '14'
  LogrotatePurgeAfterDays:
    description: Enforces life time (days) of rotated and compressed files.
    type: string
    default: '14'
  LogrotateDateExt:
    description: Enable/disable dateext parameter.
    type: boolean
    default: false
  LogrotateDateFormat:
    description: Configures dateformat strings for containerized logrotate.
                 This is valid when LogrotateDateExt is true.
                 The allowed specifiers are only %Y %m %d %H %M %S %V and %s.
    type: string
    default: '-%Y%m%d'
    constraints:
      - allowed_pattern: '-(%[YmdHMSVs])+$'
  LogrotateDateYesterday:
    description: Configures dateyesterday paramter for containerized logrotate.
                 This is valid when LogrotateDateExt is true.
    type: boolean
    default: false
  LogrotateRotateSu:
    description: Rotate log files set under this user and group instead of
                 using default user/group.
    type: string
    default: 'root root'

conditions:

  logrotatedateext_is_enabled: {equals: [{get_param: LogrotateDateExt}, true]}


resources:

  ContainersCommon:
    type: ./containers-common.yaml

outputs:
  role_data:
    description: Role data for the crond role.
    value:
      service_name: logrotate_crond
      config_settings:
        map_merge:
          - tripleo::profile::base::logging::logrotate::maxsize: {get_param: LogrotateMaxsize}
            tripleo::profile::base::logging::logrotate::rotation: {get_param: LogrotateRotationInterval}
            tripleo::profile::base::logging::logrotate::rotate: {get_param: LogrotateRotate}
            tripleo::profile::base::logging::logrotate::purge_after_days: {get_param: LogrotatePurgeAfterDays}
            tripleo::profile::base::logging::logrotate::dateext: {get_param: LogrotateDateExt}
            tripleo.contrail_logrotate_config.su: {get_param: LogrotateRotateSu}
          - if:
            - logrotatedateext_is_enabled
            - tripleo::profile::base::logging::logrotate::dateformat: {get_param: LogrotateDateFormat}
              tripleo::profile::base::logging::logrotate::dateyesterday: {get_param: LogrotateDateYesterday}
            - {}
      host_prep_tasks:
      puppet_config:
        config_volume: crond
        step_config: 'include ::tripleo::contrail_logrotate_config'
        config_image: {get_param: DockerCrondConfigImage}
