heat_template_version: queens

description:  Configures Contrail registries

# Parameters passed from the parent template - note if you maintain
# out-of-tree templates they may require additional parameters if the
# in-tree templates add a new role.
parameters:
  ContrailRegistryCertUrl:
    default: ''
    description: URL to registry certificate
    type: string
  ContrailRegistryInsecure:
    default: false
    description: Contrail Registry
    type: boolean
  ContrailRegistry:
    default: 'opencontrailnightly'
    description: Contrail Registry
    type: string
  ContrailRegistryUser:
    default: ''
    description: Contrail Registry Username
    type: string
  ContrailRegistryPassword:
    default: ''
    description: Contrail Registry Password
    type: string


resources:
  userdata:
    type: OS::Heat::MultipartMime
    properties:
      parts:
      - config: {get_resource: ContrailContainerRegistryConfig}

  ContrailContainerRegistryConfig:
    type: OS::Heat::SoftwareConfig
    properties:
      config:
        str_replace:
          template: |
            #!/bin/bash
            export LOGFILE=/tmp/contrail_trace_full.txt
            exec > >(tee -a $LOGFILE)
            exec 2>&1
            echo "=================== $(date) ==================="
            set -xv
            # disable rate limit to avoid holes in docker logs
            sed -i 's/.*RateLimitInterval.*/RateLimitInterval=0/g' /etc/systemd/journald.conf
            sed -i 's/.*RateLimitBurst.*/RateLimitBurst=0/g' /etc/systemd/journald.conf
            systemctl restart systemd-journald
            contrail_registry_insecure=$contrail_registry_insecure
            contrail_registry_cert_url=$contrail_registry_cert_url
            contrail_registry=$contrail_registry
            contrail_registry_user=$contrail_registry_user
            contrail_registry_password=$contrail_registry_password
            need_restart=0
            if [[ -n ${contrail_registry_cert_url} ]]; then
              registry_name=(${contrail_registry//:/ })
              mkdir -p /etc/docker/certs.d/${registry_name}
              (cd /etc/docker/certs.d/${registry_name}; curl -O ${contrail_registry_cert_url})
              (cd /etc/pki/ca-trust/source/anchors/; curl -O ${contrail_registry_cert_url})
              update-ca-trust
              need_restart=1
            fi
            if [[ ${contrail_registry_insecure,,} == 'true' ]]; then
              registry_name=(${contrail_registry//\// })
              found=0
              registries=`cat /etc/sysconfig/docker |grep INSECURE_REGISTRY |awk -F"--insecure-registry" '{$1="";print $0;}' |tr  "\"" " "`
              for reg in $registries; do if [[ ${reg} == ${contrail_registry} ]]; then found=1; fi; done
              if [[ ${found} -eq 0 ]]; then
                registry_string=`cat /etc/sysconfig/docker |grep INSECURE_REGISTRY |awk -F"INSECURE_REGISTRY=\"" '{print $2}'|tr "\"" " "`
                registry_string="${registry_string} --insecure-registry ${registry_name}"
                complete_string="INSECURE_REGISTRY=\"${registry_string}\""
                echo ${complete_string}
                if [[ `grep INSECURE_REGISTRY /etc/sysconfig/docker` ]]; then
                  sed -i "s/^INSECURE_REGISTRY=.*/${complete_string}/" /etc/sysconfig/docker
                else
                  echo ${complete_string} >> /etc/sysconfig/docker
                fi
                need_restart=1
              fi
            fi
            if [[ ${need_restart} -eq 0 ]]; then
              systemctl enable docker
              systemctl restart docker
            fi
            if [[ -n ${contrail_registry_user} && -n ${contrail_registry_password} ]]; then
              if [[ ${need_restart} -eq 1 ]]; then
                systemctl enable docker
                systemctl start docker
              fi
              sleep 10
              docker login -u ${contrail_registry_user} -p ${contrail_registry_password} ${contrail_registry}
            fi

          params:
            $contrail_registry_insecure: {get_param: ContrailRegistryInsecure}
            $contrail_registry_cert_url: {get_param: ContrailRegistryCertUrl}
            $contrail_registry: {get_param: ContrailRegistry}
            $contrail_registry_user: {get_param: ContrailRegistryUser}
            $contrail_registry_password: {get_param: ContrailRegistryPassword}

outputs:
  OS::stack_id:
    value: {get_resource: userdata}
