heat_template_version: ocata

parameters:
  ContrailRepo:
    type: string
    default: 'http://192.168.24.1/contrail'
  ContrailSriovOn:
    description: If SR-IOV is configured
    type: boolean
    default: false

resources:
  userdata:
    type: OS::Heat::MultipartMime
    properties:
      parts:
      - config: {get_resource: EnableContrailRepoConfig}

  EnableContrailRepoConfig:
    type: OS::Heat::SoftwareConfig
    properties:
      config:
        str_replace:
          template: |
            #!/bin/bash
            contrail_repo=$contrail_repo
            sriov_on=$sriov_on
            if [[ ${contrail_repo} ]]; then
               cat <<EOF > /etc/yum.repos.d/contrail.repo
            [Contrail]
            name=Contrail Repo
            baseurl=${contrail_repo}
            enabled=1
            gpgcheck=0
            protect=1
            metadata_expire=30
            EOF
              yum install -y contrail-tripleo-puppet puppet-contrail
              rsync -a /usr/share/contrail-tripleo-puppet/ /usr/share/openstack-puppet/modules/tripleo/
            fi
            if [[ ${sriov_on} == 'True' ]]; then
              if ! grep -q 'intel_iommu=on' /etc/default/grub ; then
                sed 's/^\(GRUB_CMDLINE_LINUX=".*\)"/\1 $KERNEL_ARGS intel_iommu=on"/g' -i /etc/default/grub ;
                grub2-mkconfig -o /etc/grub2.cfg
                reboot
              fi
            fi
          params:
            $contrail_repo: {get_param: ContrailRepo}
            $sriov_on: {get_param: ContrailSriovOn}

outputs:
  # This means get_resource from the parent template will get the userdata, see:
  # http://docs.openstack.org/developer/heat/template_guide/composition.html#making-your-template-resource-more-transparent
  # Note this is new-for-kilo, an alternative is returning a value then using
  # get_attr in the parent template instead.
  OS::stack_id:
    value: {get_resource: userdata}
